# Generated by Django 4.2.6 on 2024-05-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.categoriaproducto', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='Sin descripción', verbose_name='Descripción')),
                ('precio', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.categoriaproducto', verbose_name='Categoría')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.subcategoria', verbose_name='Subategoría')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
